baseURL = "https://www.facilitator.cards"
languageCode = "en-us"
title = "Facilitator Cards"
theme = "facilitator-cards-theme"
enableRobotsTXT = true
canonifyURLs = true

[author]
    name = "Sam Killermann & Meg Bolger"

[params]
    description = "A deck for planning, responding, and improvising -- for every facilitator, not your participants."
    keywords = "facilitator, facilitation, facilitator tools, facilitator cards, training, trainer, training tools, training planning, resources, faciliatator resources"
    images = [""] # your site-wide thumbnail image used in Twitter card and opengraph
    email_list = "http://eepurl.com/gg4Owr"

# main menu
[[menu.main]]
    name = "Cards"
    url = "/cards/"
    class = "button"
    weight = 1
[[menu.main]]
    name = "Story"
    url = "/story/"
    weight = 2

[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 3


# [[menu.main]]
#     name = "Get Your deck"
#     url = "/get/"
#     weight = 3
