baseURL = "https://www.facilitator.cards"
canonifyURLs = true
copyright = "This work is Uncopyrighted"
enableGitInfo = true
enableRobotsTXT = true
languageCode = "en-us"
paginate = 99
relativeURLs = true
title = "Facilitator Cards"
[author]
name = "Sam Killermann & Meg Bolger"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
name = "Contact Us!"
url = "/contact/"
weight = 8
[[menu.main]]
name = "The Blog"
url = "/blog/"
weight = 5
[[menu.main]]
name = "How To Use"
url = "/how/"
weight = 3
[[menu.main]]
name = "The Cards"
url = "/cards/"
weight = 2
[[menu.main]]
name = "About"
url = "/story/"
weight = 6
[[menu.main]]
name = "Preview Pack (Free!)"
url = "/preview-pack/"
weight = 7
[[menu.main]]
name = "Shop Now"
url = "https://shop.facilitator.cards/products/starter-deck/?utm_source=fc&utm_medium=nav&utm_campaign=Shop%20Now"
weight = 1
[params]
cta_link = "https://shop.facilitator.cards/products/starter-deck/?utm_source=fc&utm_medium=button&utm_campaign=Shop%20Now"
cta_text = "Shop Now"
description = "Tools for facilitation planning, running meetings with a co-facilitator, & improvising when the unexpected comes up. Creative, engaging trainings made easy."
email_list = "https://facilitatorcards.ck.page/4c87ee0944"
images = ["/img/social-share-facilitator-cards.png"]
keywords = "facilitator, facilitation, facilitator tools, facilitator cards, training, trainer, training tools, training planning, resources, faciliatator resources"
[social]
facebook = "facilitatorcards"
instagram = "facilitatorcards"
twitter = "facilitatorcard"
