baseURL = "https://www.facilitator.cards"
languageCode = "en-us"
title = "Facilitator Cards"
enableRobotsTXT = true
canonifyURLs = true
paginate = 99
enableGitInfo = true
copyright = "This work is Uncopyrighted"

[markup.goldmark.renderer]
    unsafe= true

[author]
    name = "Sam Killermann & Meg Bolger"

[social]
    twitter = "facilitatorcard"
    facebook = "facilitatorcards"
    instagram = "facilitatorcards"

[params]
    description = "Tools for facilitation planning, running meetings with a co-facilitator, & improvising when the unexpected comes up. Creative, engaging trainings made easy."
    keywords = "facilitator, facilitation, facilitator tools, facilitator cards, training, trainer, training tools, training planning, resources, faciliatator resources"
    images = ["/img/social-share-facilitator-cards.png"]
    email_list = "https://facilitatorcards.ck.page/4c87ee0944"

# main menu
[[menu.main]]
    name = "Cards"
    url = "/cards/"
    weight = 1

[[menu.main]]
    name = "Story"
    url = "/story/"
    weight = 2

[[menu.main]]
    name = "How-To"
    url = "/how/"
    weight = 2

[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4
