baseURL = "https://www.facilitator.cards"
languageCode = "en-us"
title = "Facilitator Cards"
enableRobotsTXT = true
canonifyURLs = true
paginate = 99
enableGitInfo = true
copyright = "This work is Uncopyrighted"


[author]
    name = "Sam Killermann & Meg Bolger"

[social]
    twitter = "facilitatorcard"
    facebook = "facilitatorcards"
    instagram = "facilitatorcards"

[params]
    description = "A tool for facilitation planning, responding to your group, and improvising when the unexpected comes up -- the deck of cards for every facilitator, not your participants."
    keywords = "facilitator, facilitation, facilitator tools, facilitator cards, training, trainer, training tools, training planning, resources, faciliatator resources"
    images = ["/img/social-share-facilitator-cards.png"] # your site-wide thumbnail image used in Twitter card and opengraph
    email_list = "https://facilitatorcards.ck.page/4c87ee0944"

# main menu
[[menu.main]]
    name = "Cards"
    url = "/cards/"
    class = "button"
    weight = 1

[[menu.main]]
    name = "Story"
    url = "/story/"
    weight = 2

[[menu.main]]
    name = "How-To"
    url = "/how/"
    weight = 2

[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 3
