baseURL = "https://www.facilitator.cards"
languageCode = "en-us"
title = "Facilitator Cards"
enableRobotsTXT = true
canonifyURLs = true
paginate = 99
enableGitInfo = true
copyright = "This work is Uncopyrighted"

[markup.goldmark.renderer]
    unsafe= true

[author]
    name = "Sam Killermann & Meg Bolger"

[social]
    twitter = "facilitatorcard"
    facebook = "facilitatorcards"
    instagram = "facilitatorcards"

[params]
    description = "Tools for facilitation planning, running meetings with a co-facilitator, & improvising when the unexpected comes up. Creative, engaging trainings made easy."
    keywords = "facilitator, facilitation, facilitator tools, facilitator cards, training, trainer, training tools, training planning, resources, faciliatator resources"
    images = ["/img/social-share-facilitator-cards.png"]
    email_list = "https://facilitatorcards.ck.page/4c87ee0944"
    cta_link = "https://gum.co/QYvjm"
    cta_text = "Preorder Now"

# main menu

[[menu.main]]
    name = "Shop Now"
    url = "https://shop.facilitator.cards/"
    weight = 1

[[menu.main]]
    name = "The Cards"
    url = "/cards/"
    weight = 2

[[menu.main]]
    name = "Our Story"
    url = "/story/"
    weight = 4

[[menu.main]]
    name = "How To Use"
    url = "/how/"
    weight = 3

[[menu.main]]
    name = "The Blog"
    url = "/blog/"
    weight = 5

[[menu.main]]
    name = "Contact Meg & Sam"
    url = "/contact/"
    weight = 6
