[context.production.environment]
HUGO_ENABLEGITINFO = "true"
HUGO_ENV = "production"
HUGO_VERSION = "0.70.0"

[[headers]]
for = "/img/*"
[headers.values]
Cache-Control = "public, s-max-age=604800"
[[headers]]
for = "/*.css"
[headers.values]
Cache-Control = "public, s-max-age=604800"
[[headers]]
for = "/js/*.js"
[headers.values]
Cache-Control = "public, s-max-age=604800"
